---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bingosummer/azure-cpi-e2e-test

inputs:
- name: e2e
- name: bosh-cli
- name: director-state
- name: pipelines
- name: environment

run:
  path: e2e/tasks/e2e-tests/task

params:
  AZURE_ENVIRONMENT:     ""
  AZURE_TENANT_ID:       ""
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_CLIENT_ID:       ""
  AZURE_CLIENT_SECRET:   ""
  SCENARIO:
  COUNT:                 1
