#!/bin/bash -xeu

: ${AZURE_ENVIRONMENT:?}
: ${AZURE_TENANT_ID:?}
: ${AZURE_SUBSCRIPTION_ID:?}
: ${AZURE_CLIENT_ID:?}
: ${AZURE_CLIENT_SECRET:?}

az cloud set --name ${AZURE_ENVIRONMENT}
az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID}
az account set -s ${AZURE_SUBSCRIPTION_ID}

source director-state/director.env

: ${SCENARIO:?}
: ${COUNT:?}

counter=1
while [ $counter -le $COUNT ]
do
  echo "Testing the scenario $SCENARIO; times: $counter ..."
  scenario_path="e2e/scenarios/$SCENARIO"
  ${scenario_path}/deploy $SCENARIO ${scenario_path}
  let counter=counter+1
done
