---
- type: replace
  path: /networks/-
  value:
    name: persistent-disk
    type: manual
    subnets:
    - range: 10.0.9.0/24
      gateway: 10.0.9.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.9.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-9
- type: replace
  path: /disk_types/-
  value:
    - name: 1GBReadOnly
      disk_size: 1024
      cloud_properties:
        caching: ReadOnly
    - name: 1GBReadWrite
      disk_size: 1024
      cloud_properties:
        caching: ReadWrite
