#!/bin/bash -xeu

scenario=$(basename "$PWD")
bosh -n -d $scenario deploy ./deployment.yml \
  -v scenario=$scenario \
  -v disk_type=1GB
bosh -n -d $scenario deploy ./deployment.yml \
  -v scenario=$scenario \
  -v disk_type=4TB
bosh -n -d $scenario delete-deployment
