#!/bin/bash -xeu

scenario=$1
scenario_path=$2

echo "Deploying an instance with 1GB persistent disk"
bosh -n -d $scenario deploy ${scenario_path}/deployment.yml \
  -v scenario=$scenario \
  -v disk_type=1GB

echo "Deploying an instance with 4TB persistent disk"
bosh -n -d $scenario deploy ${scenario_path}/deployment.yml \
  -v scenario=$scenario \
  -v disk_type=4TB

bosh -n -d $scenario delete-deployment
