---
- type: replace
  path: /networks/-
  value:
    name: dynamic-network
    type: dynamic
    subnets:
    - azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-8
