---
- type: replace
  path: /networks/-
  value:
    name: availability-sets
    type: manual
    subnets:
    - range: 10.0.10.0/24
      gateway: 10.0.10.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.10.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-10
- type: replace
  path: /vm_extensions/-
  value:
    name: availability-sets
    cloud_properties:
      availability_set: e2e-availability-sets
      platform_update_domain_count: 5
      platform_fault_domain_count: 2
