---
- type: replace
  path: /networks/-
  value:
    name: managed-identity
    type: manual
    subnets:
    - range: 10.0.11.0/24
      gateway: 10.0.11.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.11.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-11
- type: replace
  path: /vm_extensions/-
  value:
    name: system-assigned-managed-identity
    cloud_properties:
      managed_identity:
        type: SystemAssigned
- type: replace
  path: /vm_extensions/-
  value:
    name: user-assigned-managed-identity
    cloud_properties:
      managed_identity:
        type: UserAssigned
        user_assigned_identity_name: ((user_assigned_identity_name))
