#!/bin/bash -xeu

scenario=$(basename "$PWD")
echo "Deploying an instance with default managed identity"
bosh -n -d $scenario deploy ./deployment.yml -v scenario=$scenario
echo "Deploying an instance with system assigned managed identity in vm_extensions"
bosh -n -d $scenario deploy ./deployment.yml -v scenario=$scenario \
  -o ./use-system-assigned-managed-identity.yml
echo "Deploying an instance with user assigned managed identity in vm_extensions"
bosh -n -d $scenario deploy ./deployment.yml -v scenario=$scenario \
  -o ./use-user-assigned-managed-identity.yml
bosh -n -d $scenario delete-deployment
