---
- type: replace
  path: /networks/-
  value:
    name: zonal-load-balancer
    type: manual
    subnets:
    - range: 10.0.18.0/24
      gateway: 10.0.18.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.18.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-18
- type: replace
  path: /vm_extensions/-
  value:
    name: zonal-load-balancer-standard
    cloud_properties:
      load_balancer: ((standard_lb_name))
