---
- type: replace
  path: /networks/-
  value:
    name: persistent-disk-managed
    type: manual
    subnets:
    - range: 10.0.17.0/24
      gateway: 10.0.17.1
      azs: [z1, z2, z3]
      dns: [168.63.129.16, 8.8.8.8]
      reserved: [10.0.17.0/30]
      cloud_properties:
        security_group: ((default_security_group))
        virtual_network_name: ((vnet_name))
        subnet_name: subnet-17
- type: replace
  path: /disk_types/-
  value:
    - name: 1GBStandardLRS
      disk_size: 1024
      cloud_properties:
        storage_account_type: Standard_LRS
    - name: 1GBStandardSSDLRS
      disk_size: 1024
      cloud_properties:
        storage_account_type: StandardSSD_LRS
    - name: 1GBPremiumLRS
      disk_size: 1024
      cloud_properties:
        storage_account_type: Premium_LRS
