#!/bin/bash -xeu

scenario=$1
scenario_path=$2

echo "Case: size 1GB, type StandardLRS"
bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario \
  -v vm_type=D1v2 \
  -v disk_type=1GBStandardLRS

echo "Case: size 1GB, type StandardSSDLRS"
bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario \
  -v vm_type=D1v2 \
  -v disk_type=1GBStandardSSDLRS

echo "Case: size 1GB, type PremiumLRS"
bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario \
  -v vm_type=DS1v2 \
  -v disk_type=1GBPremiumLRS

bosh -n -d $scenario delete-deployment
