#!/bin/bash -xeu

scenario=$1
scenario_path=$2

# Update a VM with the vm_strategy: create-swap-delete
bosh -n -d $scenario deploy e2e/manifests/deployment.yml \
  -o ${scenario_path}/ops.yml \
  -v scenario=$scenario \
  -v vm_type=small

bosh -n -d $scenario delete-deployment
