#!/bin/bash -xeu

scenario=$1
scenario_path=$2

bosh -n -d $scenario deploy ${scenario_path}/deployment.yml \
  -v scenario=$scenario \
  -v vm_type=minimal

bosh -n -d $scenario deploy ${scenario_path}/deployment.yml \
  -v scenario=$scenario \
  -v vm_type=small

bosh -n -d $scenario delete-deployment
